# Generated by Django 5.2.17 on 2026-09-23 06:05

import apps.ingestion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=400, upload_to=apps.ingestion.models.original_upload_to)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size', models.PositiveBigIntegerField()),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=8)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='ingestion.supplier')),
            ],
            options={
                'verbose_name': '原始文件',
                'verbose_name_plural': '原始文件',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', '进行中'), ('succeeded', '成功'), ('failed', '失败'), ('duplicate', '重复文件')], db_default='running', max_length=16)),
                ('partial', models.BooleanField(default=False, help_text='增补文件：不做“本次未出现”判定')),
                ('mapping', models.JSONField(blank=True, default=dict, help_text='本次使用的表头识别与列映射')),
                ('ruleset_version', models.CharField(blank=True, max_length=32)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict, help_text='未识别列、未出现条目等')),
                ('error', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ingestion.sourcefile')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('locator', models.JSONField(help_text='{"sheet": .., "row": ..} 或 {"page": .., "table": .., "row": ..}')),
                ('locator_label', models.CharField(max_length=400)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('supplier_part_no', models.CharField(blank=True, max_length=100)),
                ('raw_data', models.JSONField(help_text='原表头 → 原值（文本）')),
                ('mapped', models.JSONField(default=dict, help_text='语义字段 → {value, column}')),
                ('row_hash', models.CharField(max_length=64)),
                ('diff_status', models.CharField(choices=[('new', '新增'), ('unchanged', '未变'), ('updated', '更新'), ('conflict', '冲突'), ('duplicate', '文件内重复'), ('invalid', '无法识别')], max_length=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.importbatch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ingestion.supplier')),
            ],
            options={
                'verbose_name': '原始记录',
                'verbose_name_plural': '原始记录',
                'ordering': ['batch_id', 'id'],
                'indexes': [models.Index(fields=['supplier', 'supplier_part_no'], name='ingestion_s_supplie_f3ba61_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'locator_label'), name='uniq_record_locator_per_batch')],
            },
        ),
    ]
