# Generated by Django 5.2.17 on 2026-09-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerecord',
            name='raw_data',
            field=models.JSONField(help_text='[[原表头, 原值（文本）], ...]，保持原列顺序'),
        ),
    ]
