# Generated by Django 5.2.17 on 2026-09-23 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('error', '错误'), ('warning', '警告'), ('info', '提示')], max_length=8)),
                ('field', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', '未处理'), ('resolved', '已解决'), ('ignored', '忽略')], default='open', max_length=10)),
                ('resolution_note', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ingestion.importbatch')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='catalog.supplieritem')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ingestion.sourcerecord')),
            ],
            options={
                'verbose_name': '异常',
                'verbose_name_plural': '异常',
                'ordering': ['status', 'severity', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(choices=[('auto_confirmed', '已确认归一（规则）'), ('suspect', '疑似重复'), ('auto_rejected', '规则排除')], max_length=16)),
                ('status', models.CharField(choices=[('accepted', '已合并'), ('pending', '待确认'), ('rejected', '不是同一产品'), ('needs_info', '待补充资料'), ('superseded', '已失效')], max_length=16)),
                ('decided_by', models.CharField(choices=[('rule', '规则'), ('human', '人工')], default='rule', max_length=8)),
                ('priority', models.PositiveSmallIntegerField(default=9, help_text='越小越优先')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('reasons', models.JSONField(default=list, help_text='原因码列表')),
                ('comparisons', models.JSONField(default=dict, help_text='字段 → {result, a, b}')),
                ('conflicts', models.JSONField(default=list)),
                ('missing', models.JSONField(default=list)),
                ('suggested_action', models.TextField(blank=True)),
                ('ruleset_version', models.CharField(max_length=32)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('rule_classification', models.CharField(blank=True, choices=[('auto_confirmed', '已确认归一（规则）'), ('suspect', '疑似重复'), ('auto_rejected', '规则排除')], help_text='规则最近一次给出的分类（人工决定后仍保留，便于对照）', max_length=16)),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_as_a', to='catalog.supplieritem')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_as_b', to='catalog.supplieritem')),
            ],
            options={
                'verbose_name': '匹配候选',
                'verbose_name_plural': '匹配候选',
                'ordering': ['priority', '-confidence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('merge', '确认合并'), ('reject', '不是同一产品'), ('needs_info', '待补充资料'), ('reopen', '重新打开'), ('rule', '规则决定'), ('resolve', '异常已解决'), ('ignore', '异常忽略')], max_length=16)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('via', models.CharField(choices=[('web', 'Web'), ('xlsx', 'xlsx 回写'), ('admin', 'Admin'), ('system', '系统')], max_length=8)),
                ('note', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='matching.matchcandidate')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='matching.issue')),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
                'ordering': ['-created', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'code'], name='matching_is_status_f3343d_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(('source_record__isnull', False)), fields=('source_record', 'code', 'field'), name='uniq_issue_per_record'),
        ),
        migrations.AddIndex(
            model_name='matchcandidate',
            index=models.Index(fields=['status', 'priority'], name='matching_ma_status_c094b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchcandidate',
            constraint=models.UniqueConstraint(fields=('item_a', 'item_b'), name='uniq_candidate_pair'),
        ),
        migrations.AddConstraint(
            model_name='matchcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('item_a__lt', models.F('item_b'))), name='candidate_pair_ordered'),
        ),
        migrations.AddConstraint(
            model_name='reviewdecision',
            constraint=models.CheckConstraint(condition=models.Q(('candidate__isnull', False), ('issue__isnull', False), _connector='OR'), name='decision_has_target'),
        ),
    ]
