# Generated by Django 5.2.17 on 2026-09-23 06:05

import django.contrib.postgres.fields
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=32)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_value', models.JSONField(blank=True, null=True)),
                ('source_column', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '字段来源',
                'verbose_name_plural': '字段来源',
                'ordering': ['item_id', 'field', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('supplier_sku', '供应商/品牌编号'), ('oe', 'OE/交叉参考号')], max_length=16)),
                ('number_raw', models.CharField(max_length=100)),
                ('number_norm', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': '编号',
                'verbose_name_plural': '编号',
                'ordering': ['kind', 'number_norm'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', '有效'), ('retired', '已并入/退役')], db_default='active', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('position', models.CharField(blank=True, max_length=16)),
                ('fitment_label', models.CharField(blank=True, max_length=200)),
                ('dims_label', models.CharField(blank=True, max_length=64)),
                ('attr_consensus', models.JSONField(blank=True, default=dict, help_text='字段 → {value, agreed: bool, values: [...]}')),
            ],
            options={
                'verbose_name': '归一产品',
                'verbose_name_plural': '归一产品',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('supplier_part_no', models.CharField(max_length=100)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('position', models.CharField(blank=True, max_length=16)),
                ('fitment_make', models.CharField(blank=True, max_length=64)),
                ('fitment_model', models.CharField(blank=True, max_length=64)),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dims_cm', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=3)),
                ('oe_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('attr_hash', models.CharField(help_text='关键归一属性的哈希，用作匹配证据指纹', max_length=64)),
                ('present_in_latest', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '供应商条目',
                'verbose_name_plural': '供应商条目',
                'ordering': ['supplier__code', 'supplier_part_no'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('moq', models.PositiveIntegerField(blank=True, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '供应商报价',
                'verbose_name_plural': '供应商报价',
                'ordering': ['item_id', '-quote_date', '-created'],
            },
        ),
    ]
