# Generated by Django 5.2.17 on 2026-09-23 06:05

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='source_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_values', to='ingestion.sourcerecord'),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='source_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.sourcerecord'),
        ),
        migrations.AddField(
            model_name='product',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='current_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.sourcerecord'),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ingestion.supplier'),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='catalog.supplieritem'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='catalog.supplieritem'),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.supplieritem'),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='source_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='ingestion.sourcerecord'),
        ),
        migrations.AddIndex(
            model_name='supplieritem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['oe_numbers'], name='item_oe_gin'),
        ),
        migrations.AddIndex(
            model_name='supplieritem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='item_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='supplieritem',
            index=models.Index(fields=['category', 'fitment_make', 'fitment_model'], name='catalog_sup_categor_8b1688_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(fields=('supplier', 'supplier_part_no'), name='uniq_item_per_supplier'),
        ),
        migrations.AddIndex(
            model_name='partnumber',
            index=django.contrib.postgres.indexes.GinIndex(fields=['number_norm'], name='pn_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='partnumber',
            constraint=models.UniqueConstraint(fields=('item', 'kind', 'number_norm'), name='uniq_part_number_per_item'),
        ),
        migrations.AddConstraint(
            model_name='fieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('item', 'field'), name='uniq_current_field_value'),
        ),
        migrations.AddConstraint(
            model_name='supplieroffer',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='offer_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplieroffer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('item',), name='uniq_current_offer'),
        ),
    ]
