# Generated by Django 5.2.17 on 2026-09-28 15:38

import apps.catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict, help_text='未匹配的行、无法解析的行')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '库存导入',
                'verbose_name_plural': '库存导入',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(height_field='height', max_length=300, upload_to=apps.catalog.models.item_image_upload_to, width_field='width')),
                ('thumbnail', models.ImageField(blank=True, max_length=300, upload_to=apps.catalog.models.item_thumb_upload_to)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('supplier', '供应商提供'), ('own_photo', '自己拍摄'), ('catalog', '目录截图'), ('other', '其他')], default='supplier', max_length=16)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.supplieritem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SKU 图片',
                'verbose_name_plural': 'SKU 图片',
                'ordering': ['item_id', '-is_primary', 'created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('item',), name='uniq_primary_image_per_item')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('warehouse', models.CharField(default='主仓', max_length=64)),
                ('quantity', models.IntegerField()),
                ('as_of', models.DateField(help_text='库存截至日期')),
                ('source', models.CharField(choices=[('manual', '手工录入'), ('import', '库存表导入')], max_length=8)),
                ('locator', models.CharField(blank=True, help_text='导入文件中的位置', max_length=300)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.supplieritem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='catalog.stockimport')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'ordering': ['item_id', 'warehouse', '-is_current', '-as_of', '-created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('item', 'warehouse'), name='uniq_current_stock_per_warehouse'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_non_negative')],
            },
        ),
    ]
